# Generated by Django 5.2.5 on 2025-09-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='book_covers/'),
        ),
    ]
